[package]
name = "clobber"
version = "0.1.1"
authors = ["ragona <ryanragona@gmail.com>"]
edition = "2018"
description = "Stress testing. In early development, should not be used."
license = "MIT"

[dependencies]
failure = "0.1.5"
futures-preview = "0.3.0-alpha.17"
romio = "0.3.0-alpha.9"
juliex = "0.3.0-alpha.7"