[package]
name = "clobber"
version = "0.3.0"
authors = ["ragona <ryanragona@gmail.com>"]
edition = "2018"
description = "TCP load testing tool, written in async Rust"
license = "MIT"
repository = "https://github.com/ragona/clobber"

[dependencies]
log = "0.4.7"
ctrlc = "3.1.3"
clap = "2.33.0"
fern = "0.5.8"
rand = "0.7.0"
toml = "0.5.5"
chrono = "0.4.7"
serde = "1.0.102"
num_cpus = "1.10.1"
humantime = "1.2.0"
async-std = "1.2.0"
spin_sleep = "0.3.7"
futures-timer = "0.3.0"
serde_derive = "1.0.102"
crossbeam-channel = "0.4.0"
futures-preview = "0.3.0-alpha.17"
byte-mutator = "0.1.1" 

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "clobber_bench"
harness = false
