[package]
name = "clobber"
version = "0.1.1"
authors = ["ragona <ryanragona@gmail.com>"]
edition = "2018"
description = "Stress testing. In early development, should not be used."
license = "MIT"

[dependencies]
log = "0.4.7"
ctrlc = "3.1.3"
clap = "2.33.0"
fern = "0.5.8"
chrono = "0.4.7"
failure = "0.1.5"
spin_sleep = "0.3.7"
crossbeam-channel = "0.3.9"